load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

new_local_repository(
    name = "erlnif",
    path = "/usr/lib/erlang/erts-12.1.5/include",
    build_file_content = """
package(default_visibility = ["//visibility:public"])
cc_library(
    name = "headers",
    hdrs = glob(["**/*.h"])
)
"""
)

http_archive(
    name = "ydf",
    urls = ["https://github.com/google/yggdrasil-decision-forests/archive/refs/heads/main.zip"],
    strip_prefix = "yggdrasil-decision-forests-main",
)

# You can download and configure the yggdrasil project locally, 
# comment the block http_archive above and uncomment the code below.
# local_repository(
#     name = "ydf",
#     path = "/home/projects/yggdrasil-decision-forests/",
# )

load("@ydf//yggdrasil_decision_forests:library.bzl", ydf_load_deps = "load_dependencies")
ydf_load_deps(repo_name = "@ydf")

http_archive(
    name = "org_tensorflow",
    sha256 = "e3d0ee227cc19bd0fa34a4539c8a540b40f937e561b4580d4bbb7f0e31c6a713",
    strip_prefix = "tensorflow-2.5.0",
    urls = ["https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.5.0.zip"],
)

load("@org_tensorflow//tensorflow:workspace3.bzl", tf1="workspace")
tf1()
load("@org_tensorflow//tensorflow:workspace2.bzl", tf2="workspace")
tf2()
load("@org_tensorflow//tensorflow:workspace1.bzl", tf3="workspace")
tf3()
load("@org_tensorflow//tensorflow:workspace0.bzl", tf4="workspace")
tf4()
